["Wrap Capresse",
"Wrap Queso",
"Wrap Caesar",
"Wrap Pollo",
"Wrap Primavera",
"Wrap Quinoa",
"Ensalada Nutritiva",
"Ensalada de Pollo",
"Ensalada de Calabaza",
"Ensalada Caesar",
"Ensalada de Quinoa",
"Ensalada Popeye",
"Ensalada Integral",
"Milanesa de pollo con guarnición",
"Milanesa de ternera con guarnición",
"Milanesa de berenjena con guarnición",
"Pollo al horno con guarnición",
"Albóndigas con guarnición",
"Pastel de papa",
"Lasagna Vegetariana",
"Empanadas de carne",
"Empanadas de jamón y queso",
"Empanadas de soja texturizada",
"Buñuelos de verdura",
"Ñoquis con salsa rosa",
"Ñoquis con salsa bolognesa",
"Sandwich de berenjena",
"Sandwich de Pollo",
"Sandwich Vegetariano",
"Sandwich Natural",
"Sandwich Tibio de Pollo",
"Sandwich de Milanesa de Pollo",
"Sandwich de Milanesa de Ternera",
"Sandwich de Bondiola",
"Hamburguesa Casera"]
